# -*- coding,  utf-8 -*-

from .BaseDataBaseTableManager import BaseDataBaseTableManager

class CommitmentsOfTradersLongFormatTableManager(BaseDataBaseTableManager):
    def __init__(self):
        super().__init__()
        self.sql_create_table = """
            CREATE TABLE IF NOT EXISTS TBL_COMMITMENTSOFTRADERS_LONGFORMAT (
                Market_and_Exchange_Names TEXT,
                As_of_Date_in_Form_YYMMDD REAL,
                Report_Date_as_YYYY_MM_DD TEXT,
                CFTC_Contract_Market_Code REAL,
                CFTC_Market_Code_in_Initials TEXT,
                CFTC_Region_Code REAL,
                CFTC_Commodity_Code REAL,
                Open_Interest_All REAL,
                Noncommercial_Positions_Long_All REAL,
                Noncommercial_Positions_Short_All REAL,
                Noncommercial_Positions_Spreading_All REAL,
                Commercial_Positions_Long_All REAL,
                Commercial_Positions_Short_All REAL,
                Total_Reportable_Positions_Long_All REAL,
                Total_Reportable_Positions_Short_All REAL,
                Nonreportable_Positions_Long_All REAL,
                Nonreportable_Positions_Short_All REAL,
                Open_Interest_Old REAL,
                Noncommercial_Positions_Long_Old REAL,
                Noncommercial_Positions_Short_Old REAL,
                Noncommercial_Positions_Spreading_Old REAL,
                Commercial_Positions_Long_Old REAL,
                Commercial_Positions_Short_Old REAL,
                Total_Reportable_Positions_Long_Old REAL,
                Total_Reportable_Positions_Short_Old REAL,
                Nonreportable_Positions_Long_Old REAL,
                Nonreportable_Positions_Short_Old REAL,
                Open_Interest_Other REAL,
                Noncommercial_Positions_Long_Other REAL,
                Noncommercial_Positions_Short_Other REAL,
                Noncommercial_Positions_Spreading_Other REAL,
                Commercial_Positions_Long_Other REAL,
                Commercial_Positions_Short_Other REAL,
                Total_Reportable_Positions_Long_Other REAL,
                Total_Reportable_Positions_Short_Other REAL,
                Nonreportable_Positions_Long_Other REAL,
                Nonreportable_Positions_Short_Other REAL,
                Change_in_Open_Interest_All REAL,
                Change_in_Noncommercial_Long_All REAL,
                Change_in_Noncommercial_Short_All REAL,
                Change_in_Noncommercial_Spreading_All REAL,
                Change_in_Commercial_Long_All REAL,
                Change_in_Commercial_Short_All REAL,
                Change_in_Total_Reportable_Long_All REAL,
                Change_in_Total_Reportable_Short_All REAL,
                Change_in_Nonreportable_Long_All REAL,
                Change_in_Nonreportable_Short_All REAL,
                Pct_of_Open_Interest_OI_All REAL,
                Pct_of_OI_Noncommercial_Long_All REAL,
                Pct_of_OI_Noncommercial_Short_All REAL,
                Pct_of_OI_Noncommercial_Spreading_All REAL,
                Pct_of_OI_Commercial_Long_All REAL,
                Pct_of_OI_Commercial_Short_All REAL,
                Pct_of_OI_Total_Reportable_Long_All REAL,
                Pct_of_OI_Total_Reportable_Short_All REAL,
                Pct_of_OI_Nonreportable_Long_All REAL,
                Pct_of_OI_Nonreportable_Short_All REAL,
                Pct_of_Open_Interest_OIOld REAL,
                Pct_of_OI_Noncommercial_Long_Old REAL,
                Pct_of_OI_Noncommercial_Short_Old REAL,
                Pct_of_OI_Noncommercial_Spreading_Old REAL,
                Pct_of_OI_Commercial_Long_Old REAL,
                Pct_of_OI_Commercial_Short_Old REAL,
                Pct_of_OI_Total_Reportable_Long_Old REAL,
                Pct_of_OI_Total_Reportable_Short_Old REAL,
                Pct_of_OI_Nonreportable_Long_Old REAL,
                Pct_of_OI_Nonreportable_Short_Old REAL,
                Pct_of_Open_Interest_OI_Other REAL,
                Pct_of_OI_Noncommercial_Long_Other REAL,
                Pct_of_OI_Noncommercial_Short_Other REAL,
                Pct_of_OI_Noncommercial_Spreading_Other REAL,
                Pct_of_OI_Commercial_Long_Other REAL,
                Pct_of_OI_Commercial_Short_Other REAL,
                Pct_of_OI_Total_Reportable_Long_Other REAL,
                Pct_of_OI_Total_Reportable_Short_Other REAL,
                Pct_of_OI_Nonreportable_Long_Other REAL,
                Pct_of_OI_Nonreportable_Short_Other REAL,
                Traders_Total_All REAL,
                Traders_Noncommercial_Long_All REAL,
                Traders_Noncommercial_Short_All REAL,
                Traders_Noncommercial_Spreading_All REAL,
                Traders_Commercial_Long_All REAL,
                Traders_Commercial_Short_All REAL,
                Traders_Total_Reportable_Long_All REAL,
                Traders_Total_Reportable_Short_All REAL,
                Traders_Total_Old REAL,
                Traders_Noncommercial_Long_Old REAL,
                Traders_Noncommercial_Short_Old REAL,
                Traders_Noncommercial_Spreading_Old REAL,
                Traders_Commercial_Long_Old REAL,
                Traders_Commercial_Short_Old REAL,
                Traders_Total_Reportable_Long_Old REAL,
                Traders_Total_Reportable_Short_Old REAL,
                Traders_Total_Other REAL,
                Traders_Noncommercial_Long_Other REAL,
                Traders_Noncommercial_Short_Other REAL,
                Traders_Noncommercial_Spreading_Other REAL,
                Traders_Commercial_Long_Other REAL,
                Traders_Commercial_Short_Other REAL,
                Traders_Total_Reportable_Long_Other REAL,
                Traders_Total_Reportable_Short_Other REAL,
                Concentration_Gross_LT_4_TDR_Long_All REAL,
                Concentration_Gross_LT_4_TDR_Short_All REAL,
                Concentration_Gross_LT_8_TDR_Long_All REAL,
                Concentration_Gross_LT_8_TDR_Short_All REAL,
                Concentration_Net_LT_4_TDR_Long_All REAL,
                Concentration_Net_LT_4_TDR_Short_All REAL,
                Concentration_Net_LT_8_TDR_Long_All REAL,
                Concentration_Net_LT_8_TDR_Short_All REAL,
                Concentration_Gross_LT_4_TDR_Long_Old REAL,
                Concentration_Gross_LT_4_TDR_Short_Old REAL,
                Concentration_Gross_LT_8_TDR_Long_Old REAL,
                Concentration_Gross_LT_8_TDR_Short_Old REAL,
                Concentration_Net_LT_4_TDR_Long_Old REAL,
                Concentration_Net_LT_4_TDR_Short_Old REAL,
                Concentration_Net_LT_8_TDR_Long_Old REAL,
                Concentration_Net_LT_8_TDR_Short_Old REAL,
                Concentration_Gross_LT_4_TDR_Long_Other REAL,
                Concentration_Gross_LT_4_TDR_ShortOther REAL,
                Concentration_Gross_LT_8_TDR_Long_Other REAL,
                Concentration_Gross_LT_8_TDR_ShortOther REAL,
                Concentration_Net_LT_4_TDR_Long_Other REAL,
                Concentration_Net_LT_4_TDR_Short_Other REAL,
                Concentration_Net_LT_8_TDR_Long_Other REAL,
                Concentration_Net_LT_8_TDR_Short_Other REAL,
                Contract_Units TEXT,
                CFTC_Contract_Market_Code_Quotes REAL,
                CFTC_Market_Code_in_Initials_Quotes TEXT,
                CFTC_Commodity_Code_Quotes REAL,
                FutOnly_or_Combined TEXT,
                PRIMARY KEY (
                    Market_and_Exchange_Names,
                    Report_Date_as_YYYY_MM_DD,
                    FutOnly_or_Combined
                )
            )
        """

        self.sql_insert = """
            INSERT OR IGNORE INTO TBL_COMMITMENTSOFTRADERS_LONGFORMAT (
                Market_and_Exchange_Names,
                As_of_Date_in_Form_YYMMDD,
                Report_Date_as_YYYY_MM_DD,
                CFTC_Contract_Market_Code,
                CFTC_Market_Code_in_Initials,
                CFTC_Region_Code,
                CFTC_Commodity_Code,
                Open_Interest_All,
                Noncommercial_Positions_Long_All,
                Noncommercial_Positions_Short_All,
                Noncommercial_Positions_Spreading_All,
                Commercial_Positions_Long_All,
                Commercial_Positions_Short_All,
                Total_Reportable_Positions_Long_All,
                Total_Reportable_Positions_Short_All,
                Nonreportable_Positions_Long_All,
                Nonreportable_Positions_Short_All,
                Open_Interest_Old,
                Noncommercial_Positions_Long_Old,
                Noncommercial_Positions_Short_Old,
                Noncommercial_Positions_Spreading_Old,
                Commercial_Positions_Long_Old,
                Commercial_Positions_Short_Old,
                Total_Reportable_Positions_Long_Old,
                Total_Reportable_Positions_Short_Old,
                Nonreportable_Positions_Long_Old,
                Nonreportable_Positions_Short_Old,
                Open_Interest_Other,
                Noncommercial_Positions_Long_Other,
                Noncommercial_Positions_Short_Other,
                Noncommercial_Positions_Spreading_Other,
                Commercial_Positions_Long_Other,
                Commercial_Positions_Short_Other,
                Total_Reportable_Positions_Long_Other,
                Total_Reportable_Positions_Short_Other,
                Nonreportable_Positions_Long_Other,
                Nonreportable_Positions_Short_Other,
                Change_in_Open_Interest_All,
                Change_in_Noncommercial_Long_All,
                Change_in_Noncommercial_Short_All,
                Change_in_Noncommercial_Spreading_All,
                Change_in_Commercial_Long_All,
                Change_in_Commercial_Short_All,
                Change_in_Total_Reportable_Long_All,
                Change_in_Total_Reportable_Short_All,
                Change_in_Nonreportable_Long_All,
                Change_in_Nonreportable_Short_All,
                Pct_of_Open_Interest_OI_All,
                Pct_of_OI_Noncommercial_Long_All,
                Pct_of_OI_Noncommercial_Short_All,
                Pct_of_OI_Noncommercial_Spreading_All,
                Pct_of_OI_Commercial_Long_All,
                Pct_of_OI_Commercial_Short_All,
                Pct_of_OI_Total_Reportable_Long_All,
                Pct_of_OI_Total_Reportable_Short_All,
                Pct_of_OI_Nonreportable_Long_All,
                Pct_of_OI_Nonreportable_Short_All,
                Pct_of_Open_Interest_OIOld,
                Pct_of_OI_Noncommercial_Long_Old,
                Pct_of_OI_Noncommercial_Short_Old,
                Pct_of_OI_Noncommercial_Spreading_Old,
                Pct_of_OI_Commercial_Long_Old,
                Pct_of_OI_Commercial_Short_Old,
                Pct_of_OI_Total_Reportable_Long_Old,
                Pct_of_OI_Total_Reportable_Short_Old,
                Pct_of_OI_Nonreportable_Long_Old,
                Pct_of_OI_Nonreportable_Short_Old,
                Pct_of_Open_Interest_OI_Other,
                Pct_of_OI_Noncommercial_Long_Other,
                Pct_of_OI_Noncommercial_Short_Other,
                Pct_of_OI_Noncommercial_Spreading_Other,
                Pct_of_OI_Commercial_Long_Other,
                Pct_of_OI_Commercial_Short_Other,
                Pct_of_OI_Total_Reportable_Long_Other,
                Pct_of_OI_Total_Reportable_Short_Other,
                Pct_of_OI_Nonreportable_Long_Other,
                Pct_of_OI_Nonreportable_Short_Other,
                Traders_Total_All,
                Traders_Noncommercial_Long_All,
                Traders_Noncommercial_Short_All,
                Traders_Noncommercial_Spreading_All,
                Traders_Commercial_Long_All,
                Traders_Commercial_Short_All,
                Traders_Total_Reportable_Long_All,
                Traders_Total_Reportable_Short_All,
                Traders_Total_Old,
                Traders_Noncommercial_Long_Old,
                Traders_Noncommercial_Short_Old,
                Traders_Noncommercial_Spreading_Old,
                Traders_Commercial_Long_Old,
                Traders_Commercial_Short_Old,
                Traders_Total_Reportable_Long_Old,
                Traders_Total_Reportable_Short_Old,
                Traders_Total_Other,
                Traders_Noncommercial_Long_Other,
                Traders_Noncommercial_Short_Other,
                Traders_Noncommercial_Spreading_Other,
                Traders_Commercial_Long_Other,
                Traders_Commercial_Short_Other,
                Traders_Total_Reportable_Long_Other,
                Traders_Total_Reportable_Short_Other,
                Concentration_Gross_LT_4_TDR_Long_All,
                Concentration_Gross_LT_4_TDR_Short_All,
                Concentration_Gross_LT_8_TDR_Long_All,
                Concentration_Gross_LT_8_TDR_Short_All,
                Concentration_Net_LT_4_TDR_Long_All,
                Concentration_Net_LT_4_TDR_Short_All,
                Concentration_Net_LT_8_TDR_Long_All,
                Concentration_Net_LT_8_TDR_Short_All,
                Concentration_Gross_LT_4_TDR_Long_Old,
                Concentration_Gross_LT_4_TDR_Short_Old,
                Concentration_Gross_LT_8_TDR_Long_Old,
                Concentration_Gross_LT_8_TDR_Short_Old,
                Concentration_Net_LT_4_TDR_Long_Old,
                Concentration_Net_LT_4_TDR_Short_Old,
                Concentration_Net_LT_8_TDR_Long_Old,
                Concentration_Net_LT_8_TDR_Short_Old,
                Concentration_Gross_LT_4_TDR_Long_Other,
                Concentration_Gross_LT_4_TDR_ShortOther,
                Concentration_Gross_LT_8_TDR_Long_Other,
                Concentration_Gross_LT_8_TDR_ShortOther,
                Concentration_Net_LT_4_TDR_Long_Other,
                Concentration_Net_LT_4_TDR_Short_Other,
                Concentration_Net_LT_8_TDR_Long_Other,
                Concentration_Net_LT_8_TDR_Short_Other,
                Contract_Units,
                CFTC_Contract_Market_Code_Quotes,
                CFTC_Market_Code_in_Initials_Quotes,
                CFTC_Commodity_Code_Quotes,
                FutOnly_or_Combined
            ) VALUES (
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
            )
        """
        self.create_table()

if __name__ == '__main__':
    mgr = CommitmentsOfTradersLongFormatTableManager()
    sql = 'select * from TBL_COMMITMENTSOFTRADERS_LONGFORMAT'
    # sql = "select * from TBL_COMMITMENTSOFTRADERS_LONGFORMAT where Report_Date_as_YYYY_MM_DD = '2021-04-27' and FutOnly_or_Combined = 'FutOnly'"
    dat = mgr.select(sql, True)
    df = pd.DataFrame(dat[1:], columns=dat[0])
    df.to_csv('testDF_long.csv', index=False)
