# -*- coding,  utf-8 -*-

from .BaseDataBaseTableManager import BaseDataBaseTableManager

class CommitmentsOfTradersShortFormatTableManager(BaseDataBaseTableManager):
    def __init__(self):
        super().__init__('MARKET.db')
        self.sql_create_table = """
            CREATE TABLE IF NOT EXISTS TBL_COMMITMENTSOFTRADERS_SHORTFORMAT (
                Market_and_Exchange_Names TEXT,
                As_of_Date_In_Form_YYMMDD NUMERIC,
                Report_Date_as_YYYY_MM_DD TEXT,
                CFTC_Contract_Market_Code NUMERIC,
                CFTC_Market_Code TEXT,
                CFTC_Region_Code REAL,
                CFTC_Commodity_Code REAL,
                Open_Interest_All REAL,
                Dealer_Positions_Long_All REAL,
                Dealer_Positions_Short_All REAL,
                Dealer_Positions_Spread_All REAL,
                Asset_Mgr_Positions_Long_All REAL,
                Asset_Mgr_Positions_Short_All REAL,
                Asset_Mgr_Positions_Spread_All REAL,
                Lev_Money_Positions_Long_All REAL,
                Lev_Money_Positions_Short_All REAL,
                Lev_Money_Positions_Spread_All REAL,
                Other_Rept_Positions_Long_All REAL,
                Other_Rept_Positions_Short_All REAL,
                Other_Rept_Positions_Spread_All REAL,
                Tot_Rept_Positions_Long_All REAL,
                Tot_Rept_Positions_Short_All REAL,
                NonRept_Positions_Long_All REAL,
                NonRept_Positions_Short_All REAL,
                Change_in_Open_Interest_All REAL,
                Change_in_Dealer_Long_All REAL,
                Change_in_Dealer_Short_All REAL,
                Change_in_Dealer_Spread_All REAL,
                Change_in_Asset_Mgr_Long_All REAL,
                Change_in_Asset_Mgr_Short_All REAL,
                Change_in_Asset_Mgr_Spread_All REAL,
                Change_in_Lev_Money_Long_All REAL,
                Change_in_Lev_Money_Short_All REAL,
                Change_in_Lev_Money_Spread_All REAL,
                Change_in_Other_Rept_Long_All REAL,
                Change_in_Other_Rept_Short_All REAL,
                Change_in_Other_Rept_Spread_All REAL,
                Change_in_Tot_Rept_Long_All REAL,
                Change_in_Tot_Rept_Short_All REAL,
                Change_in_NonRept_Long_All REAL,
                Change_in_NonRept_Short_All REAL,
                Pct_of_Open_Interest_All REAL,
                Pct_of_OI_Dealer_Long_All REAL,
                Pct_of_OI_Dealer_Short_All REAL,
                Pct_of_OI_Dealer_Spread_All REAL,
                Pct_of_OI_Asset_Mgr_Long_All REAL,
                Pct_of_OI_Asset_Mgr_Short_All REAL,
                Pct_of_OI_Asset_Mgr_Spread_All REAL,
                Pct_of_OI_Lev_Money_Long_All REAL,
                Pct_of_OI_Lev_Money_Short_All REAL,
                Pct_of_OI_Lev_Money_Spread_All REAL,
                Pct_of_OI_Other_Rept_Long_All REAL,
                Pct_of_OI_Other_Rept_Short_All REAL,
                Pct_of_OI_Other_Rept_Spread_All REAL,
                Pct_of_OI_Tot_Rept_Long_All REAL,
                Pct_of_OI_Tot_Rept_Short_All REAL,
                Pct_of_OI_NonRept_Long_All REAL,
                Pct_of_OI_NonRept_Short_All REAL,
                Traders_Tot_All REAL,
                Traders_Dealer_Long_All REAL,
                Traders_Dealer_Short_All REAL,
                Traders_Dealer_Spread_All REAL,
                Traders_Asset_Mgr_Long_All REAL,
                Traders_Asset_Mgr_Short_All REAL,
                Traders_Asset_Mgr_Spread_All REAL,
                Traders_Lev_Money_Long_All REAL,
                Traders_Lev_Money_Short_All REAL,
                Traders_Lev_Money_Spread_All REAL,
                Traders_Other_Rept_Long_All REAL,
                Traders_Other_Rept_Short_All REAL,
                Traders_Other_Rept_Spread_All REAL,
                Traders_Tot_Rept_Long_All REAL,
                Traders_Tot_Rept_Short_All REAL,
                Conc_Gross_LE_4_TDR_Long_All REAL,
                Conc_Gross_LE_4_TDR_Short_All REAL,
                Conc_Gross_LE_8_TDR_Long_All REAL,
                Conc_Gross_LE_8_TDR_Short_All REAL,
                Conc_Net_LE_4_TDR_Long_All REAL,
                Conc_Net_LE_4_TDR_Short_All REAL,
                Conc_Net_LE_8_TDR_Long_All REAL,
                Conc_Net_LE_8_TDR_Short_All REAL,
                Contract_Units TEXT,
                CFTC_Contract_Market_Code_Quotes NUMERIC,
                CFTC_Market_Code_Quotes TEXT,
                CFTC_Commodity_Code_Quotes NUMERIC,
                CFTC_SubGroup_Code TEXT,
                FutOnly_or_Combined TEXT,
                PRIMARY KEY (
                    Market_and_Exchange_Names,
                    Report_Date_as_YYYY_MM_DD,
                    FutOnly_or_Combined
                )
            )
        """

        self.sql_insert = """
            INSERT OR IGNORE INTO TBL_COMMITMENTSOFTRADERS_SHORTFORMAT (
                Market_and_Exchange_Names,
                As_of_Date_In_Form_YYMMDD,
                Report_Date_as_YYYY_MM_DD,
                CFTC_Contract_Market_Code,
                CFTC_Market_Code,
                CFTC_Region_Code,
                CFTC_Commodity_Code,
                Open_Interest_All,
                Dealer_Positions_Long_All,
                Dealer_Positions_Short_All,
                Dealer_Positions_Spread_All,
                Asset_Mgr_Positions_Long_All,
                Asset_Mgr_Positions_Short_All,
                Asset_Mgr_Positions_Spread_All,
                Lev_Money_Positions_Long_All,
                Lev_Money_Positions_Short_All,
                Lev_Money_Positions_Spread_All,
                Other_Rept_Positions_Long_All,
                Other_Rept_Positions_Short_All,
                Other_Rept_Positions_Spread_All,
                Tot_Rept_Positions_Long_All,
                Tot_Rept_Positions_Short_All,
                NonRept_Positions_Long_All,
                NonRept_Positions_Short_All,
                Change_in_Open_Interest_All,
                Change_in_Dealer_Long_All,
                Change_in_Dealer_Short_All,
                Change_in_Dealer_Spread_All,
                Change_in_Asset_Mgr_Long_All,
                Change_in_Asset_Mgr_Short_All,
                Change_in_Asset_Mgr_Spread_All,
                Change_in_Lev_Money_Long_All,
                Change_in_Lev_Money_Short_All,
                Change_in_Lev_Money_Spread_All,
                Change_in_Other_Rept_Long_All,
                Change_in_Other_Rept_Short_All,
                Change_in_Other_Rept_Spread_All,
                Change_in_Tot_Rept_Long_All,
                Change_in_Tot_Rept_Short_All,
                Change_in_NonRept_Long_All,
                Change_in_NonRept_Short_All,
                Pct_of_Open_Interest_All,
                Pct_of_OI_Dealer_Long_All,
                Pct_of_OI_Dealer_Short_All,
                Pct_of_OI_Dealer_Spread_All,
                Pct_of_OI_Asset_Mgr_Long_All,
                Pct_of_OI_Asset_Mgr_Short_All,
                Pct_of_OI_Asset_Mgr_Spread_All,
                Pct_of_OI_Lev_Money_Long_All,
                Pct_of_OI_Lev_Money_Short_All,
                Pct_of_OI_Lev_Money_Spread_All,
                Pct_of_OI_Other_Rept_Long_All,
                Pct_of_OI_Other_Rept_Short_All,
                Pct_of_OI_Other_Rept_Spread_All,
                Pct_of_OI_Tot_Rept_Long_All,
                Pct_of_OI_Tot_Rept_Short_All,
                Pct_of_OI_NonRept_Long_All,
                Pct_of_OI_NonRept_Short_All,
                Traders_Tot_All,
                Traders_Dealer_Long_All,
                Traders_Dealer_Short_All,
                Traders_Dealer_Spread_All,
                Traders_Asset_Mgr_Long_All,
                Traders_Asset_Mgr_Short_All,
                Traders_Asset_Mgr_Spread_All,
                Traders_Lev_Money_Long_All,
                Traders_Lev_Money_Short_All,
                Traders_Lev_Money_Spread_All,
                Traders_Other_Rept_Long_All,
                Traders_Other_Rept_Short_All,
                Traders_Other_Rept_Spread_All,
                Traders_Tot_Rept_Long_All,
                Traders_Tot_Rept_Short_All,
                Conc_Gross_LE_4_TDR_Long_All,
                Conc_Gross_LE_4_TDR_Short_All,
                Conc_Gross_LE_8_TDR_Long_All,
                Conc_Gross_LE_8_TDR_Short_All,
                Conc_Net_LE_4_TDR_Long_All,
                Conc_Net_LE_4_TDR_Short_All,
                Conc_Net_LE_8_TDR_Long_All,
                Conc_Net_LE_8_TDR_Short_All,
                Contract_Units,
                CFTC_Contract_Market_Code_Quotes,
                CFTC_Market_Code_Quotes,
                CFTC_Commodity_Code_Quotes,
                CFTC_SubGroup_Code,
                FutOnly_or_Combined
            ) VALUES (
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
            )
        """
        self.create_table()
